/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import jogo.Jogo;

/**
 *
 * @author user
 */
public class MercadoPersonagem extends javax.swing.JFrame {
    Jogo dados=null;
    int spl;
    int npc=0;
    /**
     * Creates new form Mercado
     */
    public MercadoPersonagem(Jogo jog, int pl) {
        initComponents();
        this.dados = jog;
        this.spl = pl;
        jLabel2.setText(dados.getJogador(spl).getNome());
        jLabel22.setText("Nivel: "+Integer.toString(dados.getJogador(spl).getNivel()));
        jLabel20.setText("Dinheiro: " + Double.toString(dados.getJogador(spl).getDinheiro()));
        verificaPersonagens();
        
    }

    private MercadoPersonagem() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLable_desc = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel19 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(761, 822));
        setMinimumSize(new java.awt.Dimension(761, 822));
        setPreferredSize(new java.awt.Dimension(761, 822));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/npc6.png"))); // NOI18N
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4);
        jLabel4.setBounds(450, 160, 54, 54);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bt_m.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(350, 310, 40, 40);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 0));
        jLabel18.setText("Preço");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(150, 310, 120, 20);

        jLable_desc.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLable_desc.setForeground(new java.awt.Color(204, 204, 0));
        jLable_desc.setText("<html>\"Hello world, Again, Hello world\"</html>");
        jLable_desc.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLable_desc);
        jLable_desc.setBounds(450, 300, 190, 60);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 204, 0));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/barra.png"))); // NOI18N
        jLabel20.setText("Dinheiro: 40€");
        jLabel20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel20);
        jLabel20.setBounds(280, 390, 190, 50);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/npc1.png"))); // NOI18N
        jLabel11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel11);
        jLabel11.setBounds(150, 230, 54, 54);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/npc2.png"))); // NOI18N
        jLabel12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel12);
        jLabel12.setBounds(210, 230, 54, 54);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/npc3.png"))); // NOI18N
        jLabel13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel13);
        jLabel13.setBounds(270, 230, 54, 54);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/npc4.png"))); // NOI18N
        jLabel14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel14);
        jLabel14.setBounds(330, 230, 54, 54);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/npc5.png"))); // NOI18N
        jLabel15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel15);
        jLabel15.setBounds(390, 230, 54, 54);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/npc6.png"))); // NOI18N
        jLabel16.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
        jLabel16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel16);
        jLabel16.setBounds(450, 230, 54, 54);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/npc6.png"))); // NOI18N
        jLabel17.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
        jLabel17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel17);
        jLabel17.setBounds(510, 230, 54, 54);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/npc6.png"))); // NOI18N
        jLabel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel10);
        jLabel10.setBounds(510, 160, 54, 54);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/npc5.png"))); // NOI18N
        jLabel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9);
        jLabel9.setBounds(390, 160, 54, 54);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/npc4.png"))); // NOI18N
        jLabel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8);
        jLabel8.setBounds(330, 160, 54, 54);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/npc3.png"))); // NOI18N
        jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
        jLabel7.setFocusable(false);
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7);
        jLabel7.setBounds(270, 160, 54, 54);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/npc2.png"))); // NOI18N
        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6);
        jLabel6.setBounds(210, 160, 54, 54);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/npc1.png"))); // NOI18N
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(150, 160, 54, 54);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 0));
        jLabel2.setText("Nome:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 650, 60, 20);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(204, 204, 0));
        jLabel22.setText("Nivel:");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(30, 680, 60, 20);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 204, 0));
        jLabel21.setText("Nivel Seguinte");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(30, 710, 150, 22);

        jProgressBar1.setForeground(new java.awt.Color(153, 102, 0));
        jProgressBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jProgressBar1.setStringPainted(true);
        getContentPane().add(jProgressBar1);
        jProgressBar1.setBounds(30, 740, 148, 21);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/wood menu.png"))); // NOI18N
        jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel19);
        jLabel19.setBounds(0, 630, 760, 160);

        jButton2.setFont(new java.awt.Font("Freestyle Script", 0, 36)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bt1.png"))); // NOI18N
        jButton2.setText("Voltar");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusPainted(false);
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setRequestFocusEnabled(false);
        jButton2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton2MouseMoved(evt);
            }
        });
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton2MouseReleased(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(230, 540, 280, 60);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/wood menu2.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 130, 560, 280);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Jogo\\imagens\\bg anim2.gif")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -70, 780, 780);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseMoved
        jButton2.setIcon(new ImageIcon("src\\imagens\\bt1-highlight.png"));
    }//GEN-LAST:event_jButton2MouseMoved

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        jButton2.setIcon(new ImageIcon("src\\imagens\\bt1-clicked.png"));
    }//GEN-LAST:event_jButton2MousePressed

    private void jButton2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseReleased
        jButton2.setIcon(new ImageIcon("src\\imagens\\bt1.png"));
    }//GEN-LAST:event_jButton2MouseReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Mercado mn = new Mercado(dados, spl);
        mn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
    
    
    public void verificaPersonagens(){
        ArrayList<Integer> listaindice=null;
        listaindice = dados.getPersonagensJogador(spl);
        for(int i=0; i<listaindice.size(); i++){
            switch(listaindice.get(i)){
                case 1:
                    jLabel5.setEnabled(false);
                    break;
                case 2:
                    jLabel6.setEnabled(false);
                    break;
                case 3:
                    jLabel7.setEnabled(false);
                    break;
                case 4:
                    jLabel8.setEnabled(false);
                    break;
                case 5:
                    jLabel9.setEnabled(false);
                    break;
                case 6:
                    jLabel4.setEnabled(false);
                    break;
                case 7:
                    jLabel10.setEnabled(false);
                    break;
                case 8:
                    jLabel11.setEnabled(false);
                    break;
                case 9:
                    jLabel12.setEnabled(false);
                    break;
                case 10:
                    jLabel13.setEnabled(false);
                    break;
                case 11:
                    jLabel14.setEnabled(false);
                    break;
                case 12:
                    jLabel15.setEnabled(false);
                    break;
                case 13:
                    jLabel16.setEnabled(false);
                    break;
                case 14:
                    jLabel17.setEnabled(false);
                    break;
            }
        }
    }
    
    
    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
       jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 2, true));
       jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel16.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel5.setIcon(new javax.swing.ImageIcon("src\\imagens\\npc1-ws.gif"));
       jLabel6.setIcon(new javax.swing.ImageIcon("src\\imagens\\npc2.png"));
       jLabel7.setIcon(new javax.swing.ImageIcon("src\\imagens\\npc3.png"));
       jLable_desc.setText("<html>Este personagem tem o cabelo loiro e o casaco vermelho! WOW!</html>");
       jLabel18.setText("Preço: " + Double.toString(dados.getPersona(0).getPreco())+"€");
       if (jLabel5.isEnabled()==true){
            npc=1;
       }else{npc=0;}
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
       jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 2, true));
       jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel16.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel5.setIcon(new javax.swing.ImageIcon("src\\imagens\\npc1.png"));
       jLabel7.setIcon(new javax.swing.ImageIcon("src\\imagens\\npc3.png"));
       jLabel6.setIcon(new javax.swing.ImageIcon("src\\imagens\\anime\\npc2-ws.gif"));
       jLable_desc.setText("<html>Este personagem tem o cabelo Cinzento e o casaco castanho! Quê?!</html>");
       jLabel18.setText("Preço: " + Double.toString(dados.getPersona(1).getPreco())+"€");
       if (jLabel6.isEnabled()==true){
            npc=2;
       }else{npc=0;}
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
       jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 2, true));
       jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel16.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel5.setIcon(new javax.swing.ImageIcon("src\\imagens\\npc1.png"));
       jLabel7.setIcon(new javax.swing.ImageIcon("src\\imagens\\anime\\npc3-ws.gif"));
       jLabel6.setIcon(new javax.swing.ImageIcon("src\\imagens\\npc2.png"));
       jLable_desc.setText("<html>Este personagem parece a tartaruga genial! Ai mãezina!</html>");
       jLabel18.setText("Preço: " + Double.toString(dados.getPersona(2).getPreco())+"€");
       if (jLabel7.isEnabled()==true){
            npc=3;
       }else{npc=0;}
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 2, true));
       jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel16.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel5.setIcon(new javax.swing.ImageIcon("src\\imagens\\npc1.png"));
       jLabel6.setIcon(new javax.swing.ImageIcon("src\\imagens\\npc2.png"));
       jLabel7.setIcon(new javax.swing.ImageIcon("src\\imagens\\npc3.png"));
       jLable_desc.setText("<html>Tartaruga Genial 'The Grey'!</html>");
       jLabel18.setText("Preço: " + Double.toString(dados.getPersona(3).getPreco())+"€");
       if (jLabel8.isEnabled()==true){
            npc=4;
       }else{npc=0;}
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
       jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 2, true));
       jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel16.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel5.setIcon(new javax.swing.ImageIcon("src\\imagens\\npc1.png"));
       jLabel6.setIcon(new javax.swing.ImageIcon("src\\imagens\\npc2.png"));
       jLabel7.setIcon(new javax.swing.ImageIcon("src\\imagens\\npc3.png"));
       jLabel18.setText("Preço: " + Double.toString(dados.getPersona(4).getPreco())+"€");
       jLable_desc.setText("<html>Boneca de anime!</html>");
       if (jLabel9.isEnabled()==true){
            npc=5;
       }else{npc=0;}
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
       jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 2, true));
       jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel16.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel5.setIcon(new javax.swing.ImageIcon("src\\imagens\\npc1.png"));
       jLabel6.setIcon(new javax.swing.ImageIcon("src\\imagens\\npc2.png"));
       jLabel7.setIcon(new javax.swing.ImageIcon("src\\imagens\\npc3.png"));
       jLable_desc.setText("<html>Boneca de Hentai!</html>");
       jLabel18.setText("Preço: " + Double.toString(dados.getPersona(5).getPreco())+"€");
       if (jLabel4.isEnabled()==true){
            npc=6;
       }else{npc=0;}
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
       jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel16.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel17.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 2, true));
       jLabel5.setIcon(new javax.swing.ImageIcon("src\\imagens\\npc1.png"));
       jLabel6.setIcon(new javax.swing.ImageIcon("src\\imagens\\npc2.png"));
       jLabel7.setIcon(new javax.swing.ImageIcon("src\\imagens\\npc3.png"));
       jLable_desc.setText("<html>Mais um boneco!</html>");
       jLabel18.setText("Preço: " + Double.toString(dados.getPersona(6).getPreco())+"€");
       if (jLabel10.isEnabled()==true){
            npc=7;
       }else{npc=0;}
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 2, true));
       jLabel12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel16.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel17.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel5.setIcon(new javax.swing.ImageIcon("src\\imagens\\npc1.png"));
       jLabel6.setIcon(new javax.swing.ImageIcon("src\\imagens\\npc2.png"));
       jLabel7.setIcon(new javax.swing.ImageIcon("src\\imagens\\npc3.png"));
       jLable_desc.setText("<html>Mais um boneco!</html>");
       jLabel18.setText("Preço: " + Double.toString(dados.getPersona(7).getPreco())+"€");
       if (jLabel11.isEnabled()==true){
            npc=8;
       }else{npc=0;}
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 2, true));
       jLabel13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel16.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel17.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel5.setIcon(new javax.swing.ImageIcon("src\\imagens\\npc1.png"));
       jLabel6.setIcon(new javax.swing.ImageIcon("src\\imagens\\npc2.png"));
       jLabel7.setIcon(new javax.swing.ImageIcon("src\\imagens\\npc3.png"));
       jLable_desc.setText("<html>Mais um boneco!</html>");
       jLabel18.setText("Preço: " + Double.toString(dados.getPersona(8).getPreco())+"€");
       if (jLabel12.isEnabled()==true){
            npc=9;
       }else{npc=0;}
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 2, true));
       jLabel14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel16.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel17.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel5.setIcon(new javax.swing.ImageIcon("src\\imagens\\npc1.png"));
       jLabel6.setIcon(new javax.swing.ImageIcon("src\\imagens\\npc2.png"));
       jLabel7.setIcon(new javax.swing.ImageIcon("src\\imagens\\npc3.png"));
       jLable_desc.setText("<html>Mais um boneco!</html>");
       jLabel18.setText("Preço: " + Double.toString(dados.getPersona(9).getPreco())+"€");
       if (jLabel13.isEnabled()==true){
            npc=10;
       }else{npc=0;}
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
       jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 2, true));
       jLabel15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel16.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel17.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel5.setIcon(new javax.swing.ImageIcon("src\\imagens\\npc1.png"));
       jLabel6.setIcon(new javax.swing.ImageIcon("src\\imagens\\npc2.png"));
       jLabel7.setIcon(new javax.swing.ImageIcon("src\\imagens\\npc3.png"));
       jLable_desc.setText("<html>Mais um boneco!</html>");
       jLabel18.setText("Preço: " + Double.toString(dados.getPersona(10).getPreco())+"€");
       if (jLabel14.isEnabled()==true){
            npc=11;
       }else{npc=0;}
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 2, true));
       jLabel16.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel17.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel5.setIcon(new javax.swing.ImageIcon("src\\imagens\\npc1.png"));
       jLabel6.setIcon(new javax.swing.ImageIcon("src\\imagens\\npc2.png"));
       jLabel7.setIcon(new javax.swing.ImageIcon("src\\imagens\\npc3.png"));
       jLable_desc.setText("<html>Mais um boneco!</html>");
       jLabel18.setText("Preço: " + Double.toString(dados.getPersona(11).getPreco())+"€");
       if (jLabel15.isEnabled()==true){
            npc=12;
       }else{npc=0;}
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel16.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 2, true));
       jLabel17.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel5.setIcon(new javax.swing.ImageIcon("src\\imagens\\npc1.png"));
       jLabel6.setIcon(new javax.swing.ImageIcon("src\\imagens\\npc2.png"));
       jLabel7.setIcon(new javax.swing.ImageIcon("src\\imagens\\npc3.png"));
       jLable_desc.setText("<html>Mais um boneco!</html>");
       jLabel18.setText("Preço: " + Double.toString(dados.getPersona(12).getPreco())+"€");
       if (jLabel16.isEnabled()==true){
            npc=13;
       }else{npc=0;}
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
       jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel16.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel17.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 2, true));
       jLabel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
       jLabel5.setIcon(new javax.swing.ImageIcon("src\\imagens\\npc1.png"));
       jLabel6.setIcon(new javax.swing.ImageIcon("src\\imagens\\npc2.png"));
       jLabel7.setIcon(new javax.swing.ImageIcon("src\\imagens\\npc3.png"));
       jLable_desc.setText("<html>Mais um boneco!</html>");
       jLabel18.setText("Preço: " + Double.toString(dados.getPersona(13).getPreco())+"€");
       if (jLabel17.isEnabled()==true){
            npc=14;
       }else{npc=0;}
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        jButton1.setIcon(new ImageIcon("src\\imagens\\bt_m_c.png"));
    }//GEN-LAST:event_jButton1MousePressed

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
        jButton1.setIcon(new ImageIcon("src\\imagens\\bt_m.png"));
    }//GEN-LAST:event_jButton1MouseReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      if((npc > 0) && (dados.getJogador(spl).getDinheiro() >= dados.getPersona(npc-1).getPreco()) ){
        dados.addPersonagemJogador(spl, npc-1);
        dados.setDinheiroJogador(spl, dados.getPersona(npc-1).getPreco());
          try {
              dados.gravaObj("DataObject.obj");
              jLabel20.setText("Dinheiro: " + Double.toString(dados.getJogador(spl).getDinheiro()));
          } catch (IOException ex) {
              Logger.getLogger(MercadoPersonagem.class.getName()).log(Level.SEVERE, null, ex);
          }
          switch(npc){
            case 1:
                   jLabel5.setEnabled(false);
                break;
            case 2:
                   jLabel6.setEnabled(false);
                break;
            case 3:
                   jLabel7.setEnabled(false);
                break;
            case 4:
                   jLabel8.setEnabled(false);
                break;
            case 5:
                   jLabel9.setEnabled(false);
                break;
            case 6:
                   jLabel4.setEnabled(false);
                break;
            case 7:
                   jLabel10.setEnabled(false);
                break;
            case 8:
                   jLabel11.setEnabled(false);
                break;
            case 9:
                   jLabel12.setEnabled(false);
                break;
            case 10:
                   jLabel13.setEnabled(false);
                break;
            case 11:
                   jLabel14.setEnabled(false);
                break;
            case 12:
                   jLabel15.setEnabled(false);
                break;
            case 13:
                   jLabel16.setEnabled(false);
                break;
            case 14:
                   jLabel17.setEnabled(false);
                break;
          
      }
      }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MercadoPersonagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MercadoPersonagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MercadoPersonagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MercadoPersonagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MercadoPersonagem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLable_desc;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
