/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import jogo.Jogo;

/**
 *
 * @author user
 */
public class MercadoTorres extends javax.swing.JFrame {
    Jogo dados=null;
    int spl, twr;
    /**
     * Creates new form MercadoTorres
     */
    public MercadoTorres(Jogo jog, int pl) {
        initComponents();
        dados=jog;
        spl=pl;
        twr=0;
        jLabel3.setText(dados.getJogador(spl).getNome());
        jLabel22.setText("Nivel: "+Integer.toString(dados.getJogador(spl).getNivel()));
        jLabel23.setText("Dinheiro: " + Double.toString(dados.getJogador(spl).getDinheiro()));
    }

    private MercadoTorres() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_t3 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lbl_t2 = new javax.swing.JLabel();
        lbl_t1 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLable_desc1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(761, 822));
        setMinimumSize(new java.awt.Dimension(761, 822));
        setPreferredSize(new java.awt.Dimension(761, 822));
        setResizable(false);
        getContentPane().setLayout(null);

        lbl_t3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/torre3.png"))); // NOI18N
        lbl_t3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 0), 2));
        lbl_t3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_t3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lbl_t3MouseMoved(evt);
            }
        });
        lbl_t3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_t3MouseClicked(evt);
            }
        });
        getContentPane().add(lbl_t3);
        lbl_t3.setBounds(370, 190, 50, 100);

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 204, 0));
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/barra.png"))); // NOI18N
        jLabel23.setText("Dinheiro: 40€");
        jLabel23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel23);
        jLabel23.setBounds(280, 390, 190, 50);

        lbl_t2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/torre2.png"))); // NOI18N
        lbl_t2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 0), 2));
        lbl_t2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_t2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lbl_t2MouseMoved(evt);
            }
        });
        lbl_t2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_t2MouseClicked(evt);
            }
        });
        getContentPane().add(lbl_t2);
        lbl_t2.setBounds(260, 200, 80, 80);

        lbl_t1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/torre1.png"))); // NOI18N
        lbl_t1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 0), 2));
        lbl_t1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_t1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lbl_t1MouseMoved(evt);
            }
        });
        lbl_t1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_t1MouseClicked(evt);
            }
        });
        getContentPane().add(lbl_t1);
        lbl_t1.setBounds(140, 160, 80, 130);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 204, 0));
        jLabel19.setText("Preço");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(150, 330, 130, 20);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bt_m.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton3MouseReleased(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(350, 330, 40, 40);

        jButton2.setFont(new java.awt.Font("Freestyle Script", 0, 36)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bt1.png"))); // NOI18N
        jButton2.setText("Voltar");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusPainted(false);
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setRequestFocusEnabled(false);
        jButton2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton2MouseMoved(evt);
            }
        });
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton2MouseReleased(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(230, 540, 280, 60);

        jProgressBar1.setForeground(new java.awt.Color(153, 102, 0));
        jProgressBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jProgressBar1.setStringPainted(true);
        getContentPane().add(jProgressBar1);
        jProgressBar1.setBounds(30, 740, 148, 21);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 204, 0));
        jLabel21.setText("Nivel Seguinte");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(30, 710, 150, 22);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(204, 204, 0));
        jLabel22.setText("Nivel:");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(30, 680, 60, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 0));
        jLabel3.setText("Nome:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 650, 60, 20);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/wood menu.png"))); // NOI18N
        jLabel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel20);
        jLabel20.setBounds(0, 630, 760, 160);

        jLable_desc1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLable_desc1.setForeground(new java.awt.Color(204, 204, 0));
        jLable_desc1.setText("<html>\"Hello world, Again, Hello world\"</html>");
        jLable_desc1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLable_desc1);
        jLable_desc1.setBounds(450, 310, 190, 70);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/wood menu2.png"))); // NOI18N
        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel2MouseMoved(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 130, 560, 280);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Jogo\\imagens\\bg anim2.gif")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -70, 780, 780);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_t3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_t3MouseMoved
        lbl_t3.setIcon(new javax.swing.ImageIcon("src\\imagens\\torre3-h.png"));
    }//GEN-LAST:event_lbl_t3MouseMoved

    private void lbl_t2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_t2MouseMoved
        lbl_t2.setIcon(new javax.swing.ImageIcon("src\\imagens\\torre2-h.png"));
    }//GEN-LAST:event_lbl_t2MouseMoved

    private void lbl_t1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_t1MouseMoved
        lbl_t1.setIcon(new javax.swing.ImageIcon("src\\imagens\\torre1-h.png"));
    }//GEN-LAST:event_lbl_t1MouseMoved

    private void jButton3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MousePressed
        jButton3.setIcon(new ImageIcon("src\\imagens\\bt_m_c.png"));
    }//GEN-LAST:event_jButton3MousePressed

    private void jButton3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseReleased
        jButton3.setIcon(new ImageIcon("src\\imagens\\bt_m.png"));
    }//GEN-LAST:event_jButton3MouseReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       if((twr > 0) && (dados.getJogador(spl).getDinheiro() >= dados.getTorre(twr-1).getPreco()) ){
            dados.addTorreJogador(spl, twr-1);
            dados.setDinheiroJogador(spl, dados.getTorre(twr-1).getPreco());
              try {
                  dados.gravaObj("DataObject.obj");
                  jLabel20.setText("Dinheiro: " + Double.toString(dados.getJogador(spl).getDinheiro()));
              } catch (IOException ex) {
                  Logger.getLogger(MercadoPersonagem.class.getName()).log(Level.SEVERE, null, ex);
              }
              switch(twr){
                case 1:
                       lbl_t1.setEnabled(false);
                    break;
                case 2:
                       lbl_t2.setEnabled(false);
                    break;
                case 3:
                       lbl_t3.setEnabled(false);
                    break;
                }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseMoved
        lbl_t1.setIcon(new javax.swing.ImageIcon("src\\imagens\\torre1.png"));
        lbl_t2.setIcon(new javax.swing.ImageIcon("src\\imagens\\torre2.png"));
        lbl_t3.setIcon(new javax.swing.ImageIcon("src\\imagens\\torre3.png"));
    }//GEN-LAST:event_jLabel2MouseMoved

    private void jButton2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseMoved
        jButton2.setIcon(new ImageIcon("src\\imagens\\bt1-highlight.png"));
    }//GEN-LAST:event_jButton2MouseMoved

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        jButton2.setIcon(new ImageIcon("src\\imagens\\bt1-clicked.png"));
    }//GEN-LAST:event_jButton2MousePressed

    private void jButton2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseReleased
        jButton2.setIcon(new ImageIcon("src\\imagens\\bt1.png"));
    }//GEN-LAST:event_jButton2MouseReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Mercado mn = new Mercado(dados, spl);
        mn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void lbl_t1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_t1MouseClicked
        lbl_t1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 2, true));
        lbl_t2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
        lbl_t3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
        twr=1;
        jLabel19.setText("Preço: " + Double.toString(dados.getTorre(twr-1).getPreco())+"€");
    }//GEN-LAST:event_lbl_t1MouseClicked

    private void lbl_t2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_t2MouseClicked
        lbl_t1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
        lbl_t2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 2, true));
        lbl_t3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
        twr=2;
        jLabel19.setText("Preço: " + Double.toString(dados.getTorre(twr-1).getPreco())+"€");
    }//GEN-LAST:event_lbl_t2MouseClicked

    private void lbl_t3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_t3MouseClicked
        lbl_t1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
        lbl_t2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
        lbl_t3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 2, true));
        twr=3;
        jLabel19.setText("Preço: " + Double.toString(dados.getTorre(twr-1).getPreco())+"€");
    }//GEN-LAST:event_lbl_t3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MercadoTorres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MercadoTorres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MercadoTorres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MercadoTorres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MercadoTorres().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLable_desc1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel lbl_t1;
    private javax.swing.JLabel lbl_t2;
    private javax.swing.JLabel lbl_t3;
    // End of variables declaration//GEN-END:variables
}
