/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import jogo.Jogador;
import jogo.Jogo;

/**
 *
 * @author user
 */
public class Perfil extends javax.swing.JFrame {
    Jogo dados;
    int spl=-1;
    String lbt;
    /**
     * Creates new form Perfil
     */
    public Perfil(Jogo jog) {
        initComponents();
        this.dados = jog;
        if(dados.getListaJogador().isEmpty() == false){
            if(dados.getListaJogador().size()>0){
                lbl_1.setText(dados.getJogador(0).getNome());
                lbl_e1.setEnabled(true);
            }
            if(dados.getListaJogador().size()>1){
                lbl_2.setText(dados.getJogador(1).getNome());
                lbl_e2.setEnabled(true);
            }
            if(dados.getListaJogador().size()>2){
                lbl_3.setText(dados.getJogador(2).getNome());
                lbl_e3.setEnabled(true);
            }
            if(dados.getListaJogador().size()>3){
                lbl_4.setText(dados.getJogador(3).getNome());
                lbl_e4.setEnabled(true);
            }
        }
    }

    private Perfil() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_1 = new javax.swing.JLabel();
        lbl_2 = new javax.swing.JLabel();
        lbl_3 = new javax.swing.JLabel();
        lbl_4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lbl_e1 = new javax.swing.JLabel();
        lbl_e2 = new javax.swing.JLabel();
        lbl_e3 = new javax.swing.JLabel();
        lbl_e4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 0, 0));
        setBounds(new java.awt.Rectangle(0, 0, 773, 780));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImages(null);
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(754, 803));
        setMinimumSize(new java.awt.Dimension(754, 803));
        setResizable(false);
        getContentPane().setLayout(null);

        lbl_1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_1.setForeground(new java.awt.Color(255, 0, 0));
        lbl_1.setText("Vazio");
        lbl_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_1MouseClicked(evt);
            }
        });
        getContentPane().add(lbl_1);
        lbl_1.setBounds(185, 215, 340, 76);

        lbl_2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_2.setForeground(new java.awt.Color(255, 0, 0));
        lbl_2.setText("Vazio");
        lbl_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_2MouseClicked(evt);
            }
        });
        getContentPane().add(lbl_2);
        lbl_2.setBounds(185, 309, 340, 76);

        lbl_3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_3.setForeground(new java.awt.Color(255, 0, 0));
        lbl_3.setText("Vazio");
        lbl_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_3MouseClicked(evt);
            }
        });
        getContentPane().add(lbl_3);
        lbl_3.setBounds(185, 415, 340, 76);

        lbl_4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_4.setForeground(new java.awt.Color(255, 0, 0));
        lbl_4.setText("Vazio");
        lbl_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_4MouseClicked(evt);
            }
        });
        getContentPane().add(lbl_4);
        lbl_4.setBounds(185, 517, 340, 76);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Selecione o Jogador");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(112, 123, 219, 29);

        jButton1.setFont(new java.awt.Font("Freestyle Script", 0, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bt1.png"))); // NOI18N
        jButton1.setText("Selecionar");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setEnabled(false);
        jButton1.setFocusPainted(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton1MouseMoved(evt);
            }
        });
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(80, 640, 280, 60);

        jButton2.setFont(new java.awt.Font("Freestyle Script", 0, 36)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bt1.png"))); // NOI18N
        jButton2.setText("Novo Perfil");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusPainted(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton2MouseMoved(evt);
            }
        });
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton2MouseReleased(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(390, 640, 280, 60);

        lbl_e1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/quandrado-X.png"))); // NOI18N
        lbl_e1.setEnabled(false);
        lbl_e1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_e1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_e1MouseClicked(evt);
            }
        });
        getContentPane().add(lbl_e1);
        lbl_e1.setBounds(532, 215, 78, 76);

        lbl_e2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/quandrado-X.png"))); // NOI18N
        lbl_e2.setEnabled(false);
        lbl_e2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_e2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_e2MouseClicked(evt);
            }
        });
        getContentPane().add(lbl_e2);
        lbl_e2.setBounds(532, 309, 78, 76);

        lbl_e3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/quandrado-X.png"))); // NOI18N
        lbl_e3.setEnabled(false);
        lbl_e3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_e3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_e3MouseClicked(evt);
            }
        });
        getContentPane().add(lbl_e3);
        lbl_e3.setBounds(532, 415, 78, 78);

        lbl_e4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/quandrado-X.png"))); // NOI18N
        lbl_e4.setEnabled(false);
        lbl_e4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_e4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_e4MouseClicked(evt);
            }
        });
        getContentPane().add(lbl_e4);
        lbl_e4.setBounds(532, 517, 78, 76);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bg.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel1MouseMoved(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 760, 800);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (lbt == "Vazio")  {  
            JOptionPane.showMessageDialog(null, "Escolha um jogador");
        }else{
        Password pw = new Password(dados, spl);
            pw.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lbl_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_1MouseClicked
       if(lbl_1.getText()=="Vazio"){
           lbt = "Vazio";
           jButton1.setEnabled(false);
       }else{
            
            spl = 0;
            lbt = lbl_1.getText();
            jButton1.setEnabled(true);
       }
        lbl_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl_2.setBorder(null);
        lbl_3.setBorder(null);
        lbl_4.setBorder(null);
    }//GEN-LAST:event_lbl_1MouseClicked

    private void lbl_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_2MouseClicked
        if(lbl_2.getText()=="Vazio"){
           lbt = "Vazio";
           jButton1.setEnabled(false);
       }else{
        
            spl = 1;
            lbt = lbl_2.getText();
            jButton1.setEnabled(true);
       
        }
        lbl_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl_1.setBorder(null);
        lbl_3.setBorder(null);
        lbl_4.setBorder(null);
    }//GEN-LAST:event_lbl_2MouseClicked

    private void lbl_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_3MouseClicked
         if(lbl_3.getText()=="Vazio"){
           lbt = "Vazio";
           jButton1.setEnabled(false);
       }else{   
            
            spl = 2;
            lbt = lbl_3.getText();
            jButton1.setEnabled(true);
            
         }
         lbl_3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
         lbl_2.setBorder(null);
         lbl_1.setBorder(null);
         lbl_4.setBorder(null);
    }//GEN-LAST:event_lbl_3MouseClicked

    private void lbl_4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_4MouseClicked
        if(lbl_4.getText()=="Vazio"){
           lbt = "Vazio";
           jButton1.setEnabled(false);
       }else{
            
           spl = 3;
           lbt = lbl_4.getText();
           jButton1.setEnabled(true);
           
        }
        lbl_4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl_2.setBorder(null);
        lbl_3.setBorder(null);
        lbl_1.setBorder(null);
    }//GEN-LAST:event_lbl_4MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(dados.getListaJogador().size()<4){
        String n = JOptionPane.showInputDialog("Introduza o nome:");
        if( dados.getNomeJogador(n)){
            JOptionPane.showMessageDialog(null,"Esse nome já está em uso");
        }else{
            
            JPasswordField pf = new JPasswordField();
            int okCxl = JOptionPane.showConfirmDialog(null, pf, "Introduza uma password", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        
            if (okCxl == JOptionPane.OK_OPTION) {
                char[] pwd = pf.getPassword();
                String pw="";
                for(int i=0; i<pwd.length;i++){
                    pw+= pwd[i];
                }
            
            Jogador pl = new Jogador(40, n, pw);
            dados.addJogador(pl);
            if(lbl_1.getText()=="Vazio"){
            lbl_1.setText(n);
            lbl_e1.setEnabled(true);
            }else{
                if(lbl_2.getText()=="Vazio"){
                    lbl_2.setText(n);
                    lbl_e2.setEnabled(true);
                }else{
                        if(lbl_3.getText()=="Vazio"){
                            lbl_3.setText(n);
                            lbl_e3.setEnabled(true);
                        }else{
                                lbl_4.setText(n);
                                lbl_e4.setEnabled(true);
                            }
                    }
            }
            try {
                dados.gravaObj("DataObject.obj");
            } catch (IOException ex) {
                Logger.getLogger(Opcoes.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            }}
        }else{
            JOptionPane.showMessageDialog(null, "Não pode cirar mais Jogadores");
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void lbl_e1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_e1MouseClicked
        
        if(JOptionPane.showConfirmDialog(null,"Tem a certeza que pretende eliminar este jogador?")==JOptionPane.YES_OPTION){
            if(lbl_1.getText().equals("Vazio")){
        }else{
                if(JOptionPane.showInputDialog("Introduza a password").equals(dados.getJogador(0).getPassword())){
                    String name = lbl_1.getText();
                    dados.remJogador2(name);
                    lbl_1.setText(lbl_2.getText());
                    lbl_2.setText(lbl_3.getText());
                    lbl_3.setText(lbl_4.getText());
                    lbl_4.setText("Vazio");
                    checkLabels();

                    try {
                        dados.gravaObj("DataObject.obj");
                    } catch (IOException ex) {
                        Logger.getLogger(Perfil.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
    }//GEN-LAST:event_lbl_e1MouseClicked

    private void lbl_e2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_e2MouseClicked
        if(lbl_2.getText().equals("Vazio")){
        }else{
            if(JOptionPane.showConfirmDialog(null,"Tem a certeza que pretende eliminar este jogador?")==JOptionPane.YES_OPTION){
                    if(JOptionPane.showInputDialog("Introduza a password").equals(dados.getJogador(1).getPassword())){        
                        String name = lbl_2.getText();
                       dados.remJogador2(name);
                       lbl_2.setText(lbl_3.getText());
                       lbl_3.setText(lbl_4.getText());
                       lbl_4.setText("Vazio");
                       checkLabels();
                       try {
                           dados.gravaObj("DataObject.obj");
                       } catch (IOException ex) {
                           Logger.getLogger(Perfil.class.getName()).log(Level.SEVERE, null, ex);
                       }
                    }
                }
        }
    }//GEN-LAST:event_lbl_e2MouseClicked

    private void lbl_e3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_e3MouseClicked
        if(lbl_3.getText().equals("Vazio")){
        }else{
            if(JOptionPane.showConfirmDialog(null,"Tem a certeza que pretende eliminar este jogador?")==JOptionPane.YES_OPTION){
                if(JOptionPane.showInputDialog("Introduza a password").equals(dados.getJogador(2).getPassword())){       
                    String name = lbl_3.getText();
                    dados.remJogador2(name);
                    lbl_3.setText(lbl_4.getText());
                    lbl_4.setText("Vazio");
                    checkLabels();
                    try {
                        dados.gravaObj("DataObject.obj");
                    } catch (IOException ex) {
                        Logger.getLogger(Perfil.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
    }//GEN-LAST:event_lbl_e3MouseClicked

    private void lbl_e4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_e4MouseClicked
    if(lbl_4.getText().equals("Vazio")){
    }else{    
        if(JOptionPane.showConfirmDialog(null,"Tem a certeza que pretende eliminar este jogador?")==JOptionPane.YES_OPTION){
                if(JOptionPane.showInputDialog("Introduza a password").equals(dados.getJogador(3).getPassword())){        
                    String name = lbl_4.getText();
                    dados.remJogador2(name);
                    lbl_4.setText("Vazio");
                    checkLabels();
                    try {
                        dados.gravaObj("DataObject.obj");
                    } catch (IOException ex) {
                        Logger.getLogger(Perfil.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
    }
    }//GEN-LAST:event_lbl_e4MouseClicked

    private void jButton2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseMoved
        jButton2.setIcon(new ImageIcon("src\\imagens\\bt1-highlight.png"));
    }//GEN-LAST:event_jButton2MouseMoved

    private void jLabel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseMoved
      jButton1.setIcon(new ImageIcon("src\\imagens\\bt1.png"));
      jButton2.setIcon(new ImageIcon("src\\imagens\\bt1.png"));
    }//GEN-LAST:event_jLabel1MouseMoved

    private void jButton1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseMoved
        if (jButton1.isEnabled()==true){
            jButton1.setIcon(new ImageIcon("src\\imagens\\bt1-highlight.png"));
        }
    }//GEN-LAST:event_jButton1MouseMoved

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
       jButton2.setIcon(new ImageIcon("src\\imagens\\bt1-clicked.png"));
    }//GEN-LAST:event_jButton2MousePressed

    private void jButton2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseReleased
        jButton2.setIcon(new ImageIcon("src\\imagens\\bt1.png"));
    }//GEN-LAST:event_jButton2MouseReleased

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
       if(jButton1.isEnabled()==true){
           jButton1.setIcon(new ImageIcon("src\\imagens\\bt1-clicked.png"));
       }
    }//GEN-LAST:event_jButton1MousePressed

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
        jButton1.setIcon(new ImageIcon("src\\imagens\\bt1.png"));
    }//GEN-LAST:event_jButton1MouseReleased

    public void checkLabels(){
        
        if(lbl_1.getText()=="Vazio"){
            lbl_e1.setEnabled(false);
            lbl_e2.setEnabled(false);
            lbl_e3.setEnabled(false);    
            lbl_e4.setEnabled(false);
        }else{if(lbl_2.getText()=="Vazio"){
                lbl_e2.setEnabled(false);
                lbl_e3.setEnabled(false);    
                lbl_e4.setEnabled(false);
             }else{
                if(lbl_3.getText()=="Vazio"){
                    lbl_e3.setEnabled(false);    
                    lbl_e4.setEnabled(false);
                }else{
                    if(lbl_4.getText()=="Vazio"){ 
                        lbl_e4.setEnabled(false);
                    }
                }
            }
        
        }
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Perfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lbl_1;
    private javax.swing.JLabel lbl_2;
    private javax.swing.JLabel lbl_3;
    private javax.swing.JLabel lbl_4;
    private javax.swing.JLabel lbl_e1;
    private javax.swing.JLabel lbl_e2;
    private javax.swing.JLabel lbl_e3;
    private javax.swing.JLabel lbl_e4;
    // End of variables declaration//GEN-END:variables
}
